// Copyright (c) 2017-2025 The Khronos Group Inc.
// Copyright notice at https://registry.khronos.org/speccopyright.html
//
// SPDX-License-Identifier: CC-BY-4.0

= OpenXR(TM)  Loader - Design and Operation
Copyright (c) 2017-2025 The Khronos Group Inc.
:data-uri:
:icons: font
:toc2:
:toclevels: 3
:max-width: 100
:numbered:
:imagewidth: 800
:fullimagewidth: width="800"

Copyright (c) 2017-2025 The Khronos Group Inc.
All Rights reserved.

toc::[]

include::{config}/attribs.adoc[]

[[introduction]]
= Introduction =

This document contains the necessary information for understanding how to
develop for, and interact with, the OpenXR loader.
Intended use of this document is as a detailed design document and a tool
for learning general OpenXR loader behavior.

In the event of any discrepancies between this document and the
{uri-openxr-registry-root}[OpenXR specification], that document is
authoritative.

OpenXR(TM) and the OpenXR logo are trademarks owned by The Khronos Group
Inc.
and are registered as a trademark in China, the European Union, Japan, and
the United Kingdom.
OpenGL and OpenGL ES are registered trademarks of Hewlett Packard
Enterprise, all used under license by Khronos.
All other product names, trademarks, and/or company names are used solely
for identification and belong to their respective owners.

[[introduction-terminology]]
== Terminology

The key words *must*, *may*, *can*, *cannot*, *should*, *required*,
*recommend*, and *optional* in this document are to be interpreted as
described in RFC 2119.

include::overview.adoc[]

include::application.adoc[]

include::api_layer.adoc[]

include::runtime.adoc[]

include::source.adoc[]

include::design.adoc[]

include::debug.adoc[]

include::appendices.adoc[]


