# Copyright 2022, Collabora, Ltd.
# SPDX-License-Identifier: CC0-1.0

name: OpenXR Loader for Android - Check
on:
  pull_request:

jobs:
  build-loader:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install ninja-build tool
        uses: seanmiddleditch/gha-setup-ninja@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"
          cache: gradle

      - name: Build OpenXR Loader with Gradle for Android
        run: |
          cd src/loader
          ./gradlew build
      - name: Upload OpenXR Loader for Android
        uses: actions/upload-artifact@v2
        with:
          name: OpenXR Loader for Android
          path: src/loader/build/outputs/aar/
