# Copyright 2021, Collabora, Ltd.
# SPDX-License-Identifier: CC0-1.0

name: Android Builds - Publish Snapshot
on:
  workflow_dispatch:

jobs:
  build-snapshot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install ninja-build tool
        uses: seanmiddleditch/gha-setup-ninja@v3

      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "temurin"
          cache: gradle

      - name: Build, sign, and publish AAR
        run: ./maintainer-scripts/build-and-publish-aar-snapshot.sh
        env:
          ORG_GRADLE_PROJECT_signingKey: ${{secrets.ORG_GRADLE_PROJECT_signingKey}}
          ORG_GRADLE_PROJECT_signingKeyId: ${{secrets.ORG_GRADLE_PROJECT_signingKeyId}}
          ORG_GRADLE_PROJECT_signingPassword: ${{secrets.ORG_GRADLE_PROJECT_signingPassword}}
          OSSRH_USER: ${{secrets.OSSRH_USER}}
          OSSRH_PASSWORD: ${{secrets.OSSRH_PASSWORD}}
      - name: Upload bare AAR
        uses: actions/upload-artifact@v2
        with:
          name: AAR and POM
          path: openxr_loader_for_android*
      - name: Upload Maven repo
        uses: actions/upload-artifact@v2
        with:
          name: repo
            maintainer-scripts/publish-aar/build/repo/
