# Copyright 2021-2024, Collabora, Ltd.
# SPDX-License-Identifier: CC0-1.0

name: macOS builds
on:
  workflow_call:
  workflow_dispatch:

jobs:
  macos-build:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          brew update
          brew install --formula cmake ninja
          # Add any additional dependencies here
          
      - name: Configure Build
        run: |
          mkdir build
          cd build
          cmake -G Ninja \
                -DCMAKE_BUILD_TYPE=RelWithDebInfo \
                -DCMAKE_OSX_ARCHITECTURES="x86_64;arm64" \
                -DCMAKE_INSTALL_PREFIX=../install \
                ..

      - name: Build OpenXR Loader
        run: |
          cd build
          cmake --build . --target install

      # Note: The com.apple.quarantine attribute is a macOS extended attribute that 
      # marks files as downloaded from the internet. When this flag is set, macOS’s 
      # Gatekeeper enforces security checks, prompting users to confirm whether they 
      # want to open the file. For developers who download the pre-built OpenXR Loader
      # using a web browser, they need to manually remove the quarantine attribute.
      - name: Add a note about the Quarantine flag
        run: |
          cd install
          echo "After unzipping the package, run 'xattr -d com.apple.quarantine lib/libopenxr_loader.dylib' to allow using the pre-built loader on macOS computers" > README.md

      - name: Package Artifacts
        run: |
          cd install
          tar -czvf openxr_loader_macos.tar.gz *

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: openxr_loader_macos
          path: install/openxr_loader_macos.tar.gz
