# SPDX-FileCopyrightText: 2022, Collabora, Ltd.
# SPDX-License-Identifier: CC0-1.0

on:
  workflow_call:
    inputs:
      complete:
        type: boolean
        required: true
        default: false
        description: "Whether we should be complete or fast"
      useVulkan:
        type: boolean
        required: true
        default: false
      # sourceDir:
      #   type: string
      #   required: true
      #   default: ${{ github.workspace }}
    # type: string

jobs:
  msvc-build:
    runs-on: windows-latest
    steps:
      # - uses: lukka/get-cmake@latest
      - uses: actions/checkout@v2
      - run: ./.azure-pipelines/shared/install_vulkan.ps1
        name: Install Vulkan SDK
        if: inputs.useVulkan
        working-directory: ${{ github.workspace }}
      - run: $env:VULKAN_SDK="${{ github.workspace }}/vulkan_sdk/$env:VULKAN_SDK_VERSION"
        name: Set Vulkan SDK path

      - name: Build Win32
        run: |
          cmake --preset "Win32"
          cmake --build --preset "win32_release" --parallel

      - name: Build Win32_UWP
        run: |
          cmake --preset "Win32_UWP"
          cmake --build --preset "win32_uwp_release" --parallel

      - name: Build x64
        run: |
          cmake --preset "x64"
          cmake --build --preset "x64_release" --parallel

      - name: Build x64_UWP
        run: |
          cmake --preset "x64_UWP"
          cmake --build --preset "x64_uwp_release" --parallel

      - name: Build arm_UWP
        run: |
          cmake --preset "arm_UWP"
          cmake --build --preset "arm_uwp_release" --parallel

      - name: Build arm64_UWP
        run: |
          cmake --preset "arm64_UWP"
          cmake --build --preset "arm64_uwp_release" --parallel
