# SPDX-FileCopyrightText: 2022, Collabora, Ltd.
# SPDX-License-Identifier: CC0-1.0

on:
  pull_request:

jobs:
  windows:
    uses: "rpavlik/OpenXR-SDK-Source/.github/workflows/msvc-build-preset.yml@${{github.ref}}"
